name: Test
on:
  push:
    branches:
      - solido

  pull_request:
    branches:
      - solido

jobs:
  test-github-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Package
        run: npm run package

      - name: Verify it works
        id: verify
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          list: './matrix.json'

      - name: Print output
        run: echo "Filtered list ${{ steps.verify.outputs.filtered }}"
